trajectory:
  period: 10
  raidus: 0.75
  delta_t: 0.1
  start_time: 0
uav:
  uav_num: 25
  offsets: [[0,0,1], [1,1,1], [1,-1,1], [-1,1,1], [-1,-1,1],
            [0,0,2], [1,1,2], [1,-1,2], [-1,1,2], [-1,-1,2],
            [0,0,3], [1,1,3], [1,-1,3], [-1,1,3], [-1,-1,3],
            [0,0,4], [1,1,4], [1,-1,4], [-1,1,4], [-1,-1,4],
            [0,0,5], [1,1,5], [1,-1,5], [-1,1,5], [-1,-1,5],

  ]
  weight: 1
  limit: [.inf, .inf]
